### ISSUE TITLE
AudioTag trait.

### ISSUE THREAD

**Issue by SirWindfield** [jameshurst/rust-id3#21]
Hey,

I just came across your Reddit thread were you mentioned these libraries (id3 and metaflac). What happened to the AudioTag trait? Have you replaced it.with some other unified api to access the data?

Got a question about metaflac too. How am I supposed to read the artist of flac files using your linrary? :(

**Comment by polyfloyd** [comment]
Hi, which version were you using? I can not seem to find a trait named `AudioTag` in the documentation of 0.1.12. >0.2 does not have this trait. Check out the examples on how to read a tag from a file.

Metaflac is not a part of this library, as is reading metadata from FLAC which uses Vorbis Comments for metadata. This library is primarily about the ID3 format common in MP3 and WAV files.

However, If you find a good library which handles Vorbis Comments, I would accept a patch that transcodes between formats using Rust's `From` trait.

**Comment by SirWindfield** [comment]
I was refering to [this](https://www.reddit.com/r/rust/comments/2lsfrd/rustid3_and_rustmetaflac_libraries_to_read_and/) reddit post from you where you mentioned the `AudioTag` trait. 

I am super new to rust :) Still learning the basic stuff (especially those life time markers, they are quite complicated to be honest). 
I wanted to use this library and `rust-metaflac` to read the metadata from my music collection and pass the result to be `Electron` music player. This should speed up the scan process significally compared to plain old `nodejs` file access. I am not sure though if I can compile this to `wasm`...

Back to the topic. So this library is used for ID3 tag parsing, am I right? What about `wav` files that use ID3 tags? Can I scan those too?

Did you thought about creating some kind of "parent project" that merges all your parses and offers a generic API to access the metadata from songs? That might be a cool idea. I would gladly help out if you are fine with that. Though my Rust skills are quite rusty **giggles in corner**.

**Comment by polyfloyd** [comment]
Ah, I think @jameshurst is better at answering about Metaflac and `AudioTag` then.

But yes, this library is about parsing ID3 tags. Currently, only the MP3 style of embedding, which places the tag at the start of the file, is supported. WAV files do not follow this convention because these files are split into multiple chunks with different functions. WAV is able to embed ID3 tags, but a tag has to be encoded in a separate chunk, which can be anywere in the file.

This library does have a stub where WAV support can be build upon. You could help us out with implementing ID3 in WAV support if you're interested.

I've also been busy writing a music player in Rust, including [WAV support](https://github.com/polyfloyd/audio-thing/blob/master/src/format/wave.rs#L31). Have a look if you'd like to know how parsing a WAV file works.

**Comment by jameshurst** [comment]
I can't recall exactly why I had removed the AudioTag trait but I would think a unified API would better be implemented as a separate library that abstracts over id3, metaflac, and any other metadata library. Creating a unified API that way would also mean that any other metadata type could be support without having to implement an arbitrary trait implement by these libraries.
