### ISSUE TITLE
ID3v1 support

### ISSUE THREAD

**Issue by ghost** [jameshurst/rust-id3#7]
Hello! Thanks for the library. Awesome work :+1:

Are there any plans for ID3v1 writing?
As I understand, now it removes a tag if it is present, isn't it?

**Comment by Kilte** [comment]
ping @jameshurst

**Comment by polyfloyd** [comment]
As of 0.2, ID3v1 and ID3v2 tag support has been separated. Reading v2 tags will not implicitly read v1 tags and writing v2 tags will not remove v1 tags if there are any.

More about the ID3v1 API can be found here: https://jameshurst.github.io/rust-id3/id3/v1/struct.Tag.html

Write support for ID3v1 is high on our priority list because the format has been superseded by ID3v2(.4).

**Comment by derekdreery** [comment]
I had an issue where I read a file, set the artist to something, wrote it back, read it again, and the artist was `None`. After hunting round a bit, I think this is because the file is in v1. I'll try to get a copy of the bytes causing the problem (- the music since its copywrited)

**Comment by polyfloyd** [comment]
Hi @derekdreery, could you open a new issue if you are still having this problem?
